In [16]:
import numpy as np

X = np.array([
    [2, 6, 50],
    [3, 7, 55],
    [4, 6, 60],
    [5, 8, 65],
    [6, 7, 70],
    [7, 8, 75],
    [8, 7, 80],
    [9, 8, 85]
])

y = np.array([
    48,
    55,
    61,
    68,
    73,
    80,
    86,
    92
])

print("X:")
print(X)

print("\ny:")
print(y)

X:
[[ 2  6 50]
 [ 3  7 55]
 [ 4  6 60]
 [ 5  8 65]
 [ 6  7 70]
 [ 7  8 75]
 [ 8  7 80]
 [ 9  8 85]]

y:
[48 55 61 68 73 80 86 92]


In [17]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X,y)

print("Coefficients: ",model.coef_)
print("Intercept: ",model.intercept_)

Coefficients:  [0.2363957  0.45851528 1.1819785 ]
Intercept:  -13.97564662411827


In [18]:
prediction = model.predict([[10, 8, 90]])

print("Predicted Exam Score:", prediction)

Predicted Exam Score: [98.43449782]


In [19]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("X_train:")
print(X_train)

print("\nX_test:")
print(X_test)

print("\ny_train:")
print(y_train)

print("\ny_test:")
print(y_test)

X_train:
[[ 2  6 50]
 [ 9  8 85]
 [ 4  6 60]
 [ 6  7 70]
 [ 5  8 65]
 [ 8  7 80]]

X_test:
[[ 3  7 55]
 [ 7  8 75]]

y_train:
[48 92 61 73 68 86]

y_test:
[55 80]


In [20]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

print("Coefficients: ",model.coef_)
print("Intercept: ",model.intercept_)

Coefficients:  [0.23668639 0.44230769 1.18343195]
Intercept:  -13.971893491124206


In [21]:
y_pred = model.predict(X_test)

print("Actual values: ",y_test)
print("Predicted values: ",y_pred)

Actual values:  [55 80]
Predicted values:  [54.92307692 79.98076923]


In [22]:
from sklearn.metrics import mean_squared_error,r2_score,root_mean_squared_error

mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print("R2 Score: ",r2)
print("Root Mean Squared Error: ",rmse)
print("Mean Squared Error: ",mse)

R2 Score:  0.9999798816568047
Root Mean Squared Error:  0.05606684514273653
Mean Squared Error:  0.0031434911242595983


In [23]:
prediction = model.predict([[6, 8, 72]])

print("Predicted Exam Score:", prediction)

Predicted Exam Score: [76.19378698]
