1. Introduction to KNN
2. Dataset
3. Understanding Distance
4. Finding Nearest Neighbors Manually
5. Choosing K
6. KNN with Scikit-learn
7. predict() and predict_proba()
8. Train/Test Split
9. Accuracy & Confusion Matrix
10. Feature Scaling
11. StandardScaler
12. Proper Scaling with Train/Test Data
13. Choosing K with Cross-Validation
14. Conclusion

In [66]:
import numpy as np

X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
    [7],
    [8],
    [9],
    [10]
])

y = np.array([
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1
])

print("X:")
print(X)

print("\ny:")
print(y)

X:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

y:
[0 0 0 0 0 1 1 1 1 1]


In [67]:
new_student = 6.5

distances = abs(X.flatten() - new_student)

print(distances)

[5.5 4.5 3.5 2.5 1.5 0.5 0.5 1.5 2.5 3.5]


In [68]:
k = 3

nearest_indices = np.argsort(distances)[:k]

print("Nearest Indices: ",nearest_indices)

print("Nearest Hours: ",X[nearest_indices].flatten())

print("Nearest Results: ",y[nearest_indices])

Nearest Indices:  [6 5 7]
Nearest Hours:  [7 6 8]
Nearest Results:  [1 1 1]


In [69]:
for k in [1,3,5,7]:
  nearest_indices = np.argsort(distances)[:k]
  nearest_results = y[nearest_indices]

print("K = ",k)
print("Neighbours: ",nearest_results)
print()

K =  7
Neighbours:  [1 1 1 0 0 1 1]



In [70]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [71]:
new_student = np.array([[6.5]])

model = model.predict(new_student)

print(model)

[1]


In [72]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X, y)

new_student = np.array([[6.5]])

prediction = model.predict(new_student)
probability = model.predict_proba(new_student)

print("Prediction:", prediction)
print("Probabilities:", probability)

Prediction: [1]
Probabilities: [[0.33333333 0.66666667]]


In [73]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("X_train:")
print(X_train)

print("\ny_train:")
print(y_train)

print("\nX_test:")
print(X_test)

print("\ny_test:")
print(y_test)

X_train:
[[ 6]
 [ 1]
 [ 8]
 [ 3]
 [10]
 [ 5]
 [ 4]
 [ 7]]

y_train:
[1 0 1 0 1 0 0 1]

X_test:
[[9]
 [2]]

y_test:
[1 0]


In [74]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_train,y_train)

print("KNeighbor Trained Successfully")

KNeighbor Trained Successfully


In [75]:
y_pred = model.predict(X_test)

print("Actual: ",y_test)
print("Predicted: ",y_pred)

Actual:  [1 0]
Predicted:  [1 0]


In [76]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test,y_pred)

print("Accuracy: ",accuracy)

Accuracy:  1.0


In [77]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

print("Confusion Matrix: ",cm)

Confusion Matrix:  [[1 0]
 [0 1]]


In [78]:
for k in range(1,8):
  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(X_train,y_train)

  accuracy = model.score(X_test,y_test)

  print("K: ",k,"Accuracy : ",accuracy)

K:  1 Accuracy :  1.0
K:  2 Accuracy :  1.0
K:  3 Accuracy :  1.0
K:  4 Accuracy :  1.0
K:  5 Accuracy :  1.0
K:  6 Accuracy :  1.0
K:  7 Accuracy :  1.0


In [79]:
X = np.array([
    [2, 50],
    [3, 55],
    [4, 60],
    [5, 65],
    [6, 70],
    [7, 75],
    [8, 80],
    [9, 85]
])

y = np.array([
    0, 0, 0, 0,
    1, 1, 1, 1
])

print("X: ",X)
print("Minimun value: ",X.min(axis=0))
print("Maximum value: ",X.max(axis=0))

X:  [[ 2 50]
 [ 3 55]
 [ 4 60]
 [ 5 65]
 [ 6 70]
 [ 7 75]
 [ 8 80]
 [ 9 85]]
Minimun value:  [ 2 50]
Maximum value:  [ 9 85]


In [80]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("X_scaled: ",X_scaled)

X_scaled:  [[-1.52752523 -1.52752523]
 [-1.09108945 -1.09108945]
 [-0.65465367 -0.65465367]
 [-0.21821789 -0.21821789]
 [ 0.21821789  0.21821789]
 [ 0.65465367  0.65465367]
 [ 1.09108945  1.09108945]
 [ 1.52752523  1.52752523]]


In [81]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_scaled,y)

new_student = np.array([[6,72]])

new_student_scaled = scaler.transform(new_student)

prediction = model.predict(new_student_scaled)

print("Scaled new Student: ",new_student_scaled)
print("Prediction: ",prediction)

Scaled new Student:  [[0.21821789 0.3927922 ]]
Prediction:  [1]


In [82]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled: ",X_train_scaled)
print("X_test_scaled: ",X_test_scaled)

X_train_scaled:  [[-1.55563492 -1.55563492]
 [ 1.41421356  1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.14142136  0.14142136]
 [-0.28284271 -0.28284271]
 [ 0.98994949  0.98994949]]
X_test_scaled:  [[-1.13137085 -1.13137085]
 [ 0.56568542  0.56568542]]


In [83]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_train_scaled,y_train)

y_pred = model.predict(X_test_scaled)

print("Actual: ",y_test)
print("Predicted: ",y_pred)

Actual:  [0 1]
Predicted:  [0 1]


In [84]:
from sklearn.metrics import accuracy_score

accuacy = accuracy_score(y_test,y_pred)

print("Accuracy: ",accuracy)


Accuracy:  1.0


In [85]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

for k in [1,2,3]:
  model = KNeighborsClassifier(n_neighbors=k)

  scores = cross_val_score(model,X_train_scaled,y_train,cv=3)

print("K: ",k)
print("Scores: ",scores)
print("Average: ",scores.mean())
print()

K:  3
Scores:  [1. 1. 1.]
Average:  1.0

