In [23]:
import numpy as np

X = np.array([
    ["Sunny", "Hot"],
    ["Sunny", "Cool"],
    ["Rainy", "Cool"],
    ["Rainy", "Cold"],
    ["Cloudy", "Cool"],
    ["Cloudy", "Hot"],
    ["Sunny", "Cold"],
    ["Rainy", "Hot"]
])

y = np.array([
    "No",
    "Yes",
    "Yes",
    "Yes",
    "Yes",
    "Yes",
    "No",
    "No"
])

print("X:")
print(X)

print("\ny:")
print(y)

X:
[['Sunny' 'Hot']
 ['Sunny' 'Cool']
 ['Rainy' 'Cool']
 ['Rainy' 'Cold']
 ['Cloudy' 'Cool']
 ['Cloudy' 'Hot']
 ['Sunny' 'Cold']
 ['Rainy' 'Hot']]

y:
['No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No']


In [24]:
unique_classes, counts = np.unique(y, return_counts=True)

print("Classes:", unique_classes)
print("Counts:", counts)

for cls, count in zip(unique_classes, counts):
    probability = count / len(y)
    print("P(", cls, ") =", probability)

Classes: ['No' 'Yes']
Counts: [3 5]
P( No ) = 0.375
P( Yes ) = 0.625


In [25]:
yes_data = X[y == "Yes"]

print("Yes Class Data: ",yes_data)

sunny_count = np.sum(yes_data[:, 0] == "Sunny")
cool_count = np.sum(yes_data[:, 1] == "Cool")

print("Sunny Count : ",sunny_count)
print("Cool Count: ",cool_count)

print("P(Sunny | Yes): ",sunny_count/len(yes_data))
print("P(Cool | Yes): ",cool_count/len(yes_data))

Yes Class Data:  [['Sunny' 'Cool']
 ['Rainy' 'Cool']
 ['Rainy' 'Cold']
 ['Cloudy' 'Cool']
 ['Cloudy' 'Hot']]
Sunny Count :  1
Cool Count:  3
P(Sunny | Yes):  0.2
P(Cool | Yes):  0.6


In [26]:
no_data = X[y == "No"]

print("No class data:")
print(no_data)

sunny_count = np.sum(no_data[:, 0] == "Sunny")
cool_count = np.sum(no_data[:, 1] == "Cool")

print("\nSunny count:", sunny_count)
print("Cool count:", cool_count)

print("\nP(Sunny | No):", sunny_count / len(no_data))
print("P(Cool | No):", cool_count / len(no_data))

No class data:
[['Sunny' 'Hot']
 ['Sunny' 'Cold']
 ['Rainy' 'Hot']]

Sunny count: 2
Cool count: 0

P(Sunny | No): 0.6666666666666666
P(Cool | No): 0.0


In [27]:
# Prior probabilities
p_yes = 5 / 8
p_no = 3 / 8

# Conditional probabilities with Laplace smoothing

# Yes class
p_sunny_given_yes = (1 + 1) / (5 + 3)
p_cool_given_yes = (3 + 1) / (5 + 3)

# No class
p_sunny_given_no = (2 + 1) / (3 + 3)
p_cool_given_no = (0 + 1) / (3 + 3)

# Calculate scores
score_yes = p_yes * p_sunny_given_yes * p_cool_given_yes
score_no = p_no * p_sunny_given_no * p_cool_given_no

print("Score for Yes:", score_yes)
print("Score for No:", score_no)

Score for Yes: 0.078125
Score for No: 0.03125


In [28]:
total = score_yes + score_no

prob_yes = score_yes/total
prob_no = score_no/total

print("P(Yes | Sunny,Cool): ",prob_yes)
print("P(No | Sunny,Cool): ",prob_no)

P(Yes | Sunny,Cool):  0.7142857142857143
P(No | Sunny,Cool):  0.2857142857142857


In [29]:
from sklearn.preprocessing import LabelEncoder

weather_encoder = LabelEncoder()
temp_encoder = LabelEncoder()

X_encoded = X.copy()

X_encoded[:, 0] = weather_encoder.fit_transform(X[:, 0])
X_encoded[:, 1] = temp_encoder.fit_transform(X[:, 1])

print("Encoded X:")
print(X_encoded)

Encoded X:
[['2' '2']
 ['2' '1']
 ['1' '1']
 ['1' '0']
 ['0' '1']
 ['0' '2']
 ['2' '0']
 ['1' '2']]


In [30]:
X_encoded = X_encoded.astype(int)

print("Encoded X:")
print(X_encoded)

print("\nData type:")
print(X_encoded.dtype)

Encoded X:
[[2 2]
 [2 1]
 [1 1]
 [1 0]
 [0 1]
 [0 2]
 [2 0]
 [1 2]]

Data type:
int64


In [31]:
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB()

model.fit(X_encoded,y)

print("Model trained Successfully")

Model trained Successfully


In [32]:
new_data = np.array([[2,1]])

prediction = model.predict(new_data)

print("Prediction: ",prediction)

Prediction:  ['Yes']


In [33]:
probability = model.predict_proba(new_data)

print("Probabilities: ",probability)

Probabilities:  [[0.28571429 0.71428571]]


In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.25,
    random_state=42
)

print("X_train:")
print(X_train)

print("\ny_train:")
print(y_train)

print("\nX_test:")
print(X_test)

print("\ny_test:")
print(y_test)

X_train:
[[2 2]
 [1 2]
 [1 1]
 [0 1]
 [1 0]
 [2 0]]

y_train:
['No' 'No' 'Yes' 'Yes' 'Yes' 'No']

X_test:
[[2 1]
 [0 2]]

y_test:
['Yes' 'Yes']


In [35]:
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!


In [36]:
y_pred = model.predict(X_test)

print("Actual value: ",y_test)
print("Predicted value: ",y_pred)

Actual value:  ['Yes' 'Yes']
Predicted value:  ['No' 'No']


In [37]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy: ",accuracy)


Accuracy:  0.0


In [38]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

print(cm)

[[0 0]
 [2 0]]


In [39]:
probabilities = model.predict_proba(X_test)

print("Probabilities: ",probabilities)

Probabilities:  [[0.5 0.5]
 [0.6 0.4]]
