In [12]:
import pandas as pd

data = {
    "message" : [
          "Win a free prize now",
        "Claim your cash reward",
        "Congratulations you won a lottery",
        "Free entry in a contest",
        "Hey buddy how are you",
        "Are we meeting today",
        "Please call me when you arrive",
        "Let's study together"
    ],
    "label" : [
          "spam",
        "spam",
        "spam",
        "spam",
        "not_spam",
        "not_spam",
        "not_spam",
        "not_spam"
    ]
}

df = pd.DataFrame(data)
print(df)

                             message     label
0               Win a free prize now      spam
1             Claim your cash reward      spam
2  Congratulations you won a lottery      spam
3            Free entry in a contest      spam
4              Hey buddy how are you  not_spam
5               Are we meeting today  not_spam
6     Please call me when you arrive  not_spam
7               Let's study together  not_spam


In [13]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

x = vectorizer.fit_transform(df["message"])

print("Vocabulary: ",vectorizer.get_feature_names_out())
print("\nNumerical Representation: ",x.toarray())

Vocabulary:  ['are' 'arrive' 'buddy' 'call' 'cash' 'claim' 'congratulations' 'contest'
 'entry' 'free' 'hey' 'how' 'in' 'let' 'lottery' 'me' 'meeting' 'now'
 'please' 'prize' 'reward' 'study' 'today' 'together' 'we' 'when' 'win'
 'won' 'you' 'your']

Numerical Representation:  [[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]]


In [15]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x,df["label"])

print("Spam Detection model trained successfully")

Spam Detection model trained successfully


In [16]:
new_message = ["Congratulations claim your free cash prize now"]

new_message_vector = vectorizer.transform(new_message)

prediction = model.predict(new_message_vector)

print("Message: ",new_message[0])
print("Prediction: ",prediction[0])

Message:  Congratulations claim your free cash prize now
Prediction:  spam


In [17]:
new_message = ["Hey buddy are we meeting today"]

new_message_vector = vectorizer.transform(new_message)
prediction = model.predict(new_message_vector)

print("Message: ",new_message[0])
print("Prediction: ",prediction[0])

Message:  Hey buddy are we meeting today
Prediction:  not_spam


In [19]:
new_message = ["Congratulations claim your free cash prize"]

new_message_vector = vectorizer.transform(new_message)
prediction = model.predict_proba(new_message_vector)

print("Message: ",new_message[0])
print("Probabilities: ",prediction[0])

Message:  Congratulations claim your free cash prize
Probabilities:  [0.00800457 0.99199543]


In [20]:
messages = [
    "Win a free prize now",
    "Hey buddy how are you",
    "Claim your cash reward",
    "Please call me when you arrive",
    "Congratulations you won a lottery"
]

message_vectors = vectorizer.transform(messages)
predictions = model.predict(message_vectors)

for message, prediction in zip(messages, predictions):
    print("Message:", message)
    print("Prediction:", prediction)
    print()

Message: Win a free prize now
Prediction: spam

Message: Hey buddy how are you
Prediction: not_spam

Message: Claim your cash reward
Prediction: spam

Message: Please call me when you arrive
Prediction: not_spam

Message: Congratulations you won a lottery
Prediction: spam



In [23]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

x_train,x_test,y_train,y_test = train_test_split(
    df["message"],
    df["label"],
    test_size=0.25,
    random_state=42,
    stratify=df["label"]
)

model = make_pipeline(
    CountVectorizer(),
    MultinomialNB()
)

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test,y_pred)

print("Actual: ",y_test.to_numpy())
print("Predicted: ",y_pred)
print("Accuracy: ",accuracy)

Actual:  ['not_spam' 'spam']
Predicted:  ['not_spam' 'not_spam']
Accuracy:  0.5


In [27]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred,labels=["not_spam","spam"])

print(cm)

[[1 0]
 [1 0]]
